### ISSUE TITLE
Allow setting `basicAuth: false` when doing a refresh()

### ISSUE THREAD

**Issue by dJani97** [DutchCodingCompany/oauth_chopper#24]
The default code for `OAuthChopper.refresh()` calls `oauth2.Credentials.refresh()` with these parameters:

```dart
final newCredentials = await credentials.refresh(
  identifier: identifier,
  secret: secret,
  httpClient: httpClient,
);
```

In my use-case, the default `bool basicAuth = true` parameter causes a problem, because AWS Cognito refuses such requests with a `400 { "error": "invalid_client" }` code. [See source.](https://stackoverflow.com/a/62800854/5521187)

I would suggest extending the `OAuthChopper.refresh()` method to include all optional parameters of the wrapped `oauth2.Credentials.refresh()` method:

```dart
Future<OAuthToken?> refresh({bool basicAuth = true, Iterable<String>? newScopes}) async {
  final credentialsJson = await _storage.fetchCredentials();
  if (credentialsJson == null) return null;
  final credentials = oauth2.Credentials.fromJson(credentialsJson);
  try {
    final newCredentials = await credentials.refresh(
      identifier: identifier,
      secret: secret,
      httpClient: httpClient,
      basicAuth: basicAuth,
      newScopes: newScopes,
    );
    await _storage.saveCredentials(newCredentials.toJson());
    return OAuthToken.fromCredentials(newCredentials);
  } on oauth2.AuthorizationException {
    _storage.clear();
    rethrow;
  }
}
```

**Comment by Guldem** [comment]
Thanks for the feedback! Initially I only implemented the parameters needed for our own use-cases. 

I have extended oauth_chopper to support more of the auth2 package parameters  in #25.  Including the extra refresh parameters. Hopefully this solves your problem. 

When its merged I will publish the package.
